In [15]:
import pandas as pd
import numpy as np

fish_fry = pd.read_csv("fish_fry_results.csv", index_col=0)
cost_of_living = pd.read_csv("affordability_results.csv")
safety = None #TODO

#Edit these later aswell
COST_OF_LIVING_WEIGHT = 0.34
FISH_FRY_WEIGHT       = 0.33
SAFETY_WEIGHT         = 0.33


final_df = pd.merge(fish_fry,cost_of_living,how='left', on="Neighborhood")
#final_df = final_df.merge(cost_of_living[["Neighborhood", "cost_of_living_score"]], on="Neighborhood")
#final_df = final_df.merge(cost_of_living[["Neighborhood", "safety_score"]], on="Neighborhood")

#final_df["final_score"] = (
#    final_df["cost_of_living_score"] * COST_OF_LIVING_WEIGHT +
#    final_df["fish_fry_score"]       * FISH_FRY_WEIGHT +
#    final_df["safety_score"]         * SAFETY_WEIGHT
#)

# Sort and display
#final_results = final_df[["Neighborhood", "cost_of_living_score", "fish_fry_score", "safety_score", "final_score"]].sort_values("final_score", ascending=False)
final_df

      Neighborhood  Fish_Frys  Fish_Frys_Score  cost_of_living_score
0        Aspinwall          1              0.0                   NaN
1       Wilmerding          1              0.0                   NaN
2    Slippery Rock          2              0.2                   NaN
3         Crabtree          1              0.0                   NaN
4          Wexford          2              0.2                   NaN
..             ...        ...              ...                   ...
135          15224          1              0.0                   NaN
136          15220          2              0.2                   NaN
137          15201          1              0.0                   NaN
138          15231          1              0.0                   NaN
139          15226          1              0.0                   NaN

[140 rows x 4 columns]

In [12]:
fish_fry

               Fish_Frys  Fish_Frys_Score
Neighborhood
Aspinwall              1              0.0
Wilmerding             1              0.0
Slippery Rock          2              0.2
Crabtree               1              0.0
Wexford                2              0.2
...                  ...              ...
15224                  1              0.0
15220                  2              0.2
15201                  1              0.0
15231                  1              0.0
15226                  1              0.0

[140 rows x 2 columns]

In [13]:
cost_of_living

           Neighborhood  cost_of_living_score
0              West End              0.832031
1           Beltzhoover              0.782094
2         Spring Garden              0.776069
3               Larimer              0.754040
4         Homewood West              0.743202
..                  ...                   ...
80        North Oakland             -0.039207
81           Friendship             -0.041532
82         Point Breeze             -0.060388
83            Shadyside             -0.234255
84  Squirrel Hill North             -0.417048

[85 rows x 2 columns]

## Cost of Living Score

### Process
- Selected cost of living because it is the most essential metric for evaluating neighborhoods
- Comprehensive data was difficult to find, with government census data being the most reliable source
- Two metrics required proxies due to data limitations:
    - **Transportation Cost** → Percent of residents who commute by car
    - **Rent Burden** → Median home value divided by median income
- A small number of neighborhoods had missing data, though none would have impacted the final ranking

---

### Missing Data

| Neighborhood | Missing Field | Estimated Value |
|---|---|---|
| Allegheny Center | Median Sale Price | ~$125,000 |
| Arlington Heights | Median Sale Price | ~$100,000 |
| Glen Hazel | Median Sale Price | ~$114,350 (midpoint of $83,700–$145,000 range) |
| North Shore | Median Home Value | $111,755 |
| South Shore | Median Home Value | ~$125,000 |
| Northview Heights | Median Home Value | $130,000 |
| Chateau | Multiple Fields | Not scored — sparse population and insufficient data |

---

### Affordability Rankings

<img src="affordability_rankings.png" width="600">

### Conclusion

TODO

Aaron V: